<a href="https://colab.research.google.com/github/RapNinja16/Activity5_SVM/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Preparing the data

In [23]:
#Import important libraries

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [24]:


# Importing the CSV file from google drive
from google.colab import drive

#'https://drive.google.com/file/d/16JoNZGR2rFfZn-ptstpSDK3XxLVqaq6j/view?usp=sharing'

url = 'https://drive.google.com/file/d/16JoNZGR2rFfZn-ptstpSDK3XxLVqaq6j/view?usp=sharing'
file_id = url.split('/')[-2]
drive = 'https://drive.google.com/uc?id=' + file_id
df = pd.read_csv(drive)
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0          0.0            0.0                 1.0           0       0   
1          0.0            0.0                 1.0           0       0   
2          0.0            0.0                 0.0           0       0   
3          0.0            0.0                 0.0           0       0   
4          0.0            0.0                 0.0           0       0   
...        ...            ...                 ...         ...     ...   
4995       0.0            0.0                 0.0           0       1   
4996      85.0            0.0                 0.0           0       1   
4997       0.0            0.0                 0.0           0       0   
4998       0.0            0.0                 0.0           0       1   
4999       0.0            0.0                 0.0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

Data Processing

In [25]:
#Checking for Null
df.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              2
Personal Loan         1
Securities Account    1
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [26]:
#Taking care of missing data


# .mode fills the column with the most frequent Value, This can be use for data that arent numerical
# .mean fills the column with the mean of that column

#df[''] = df[''].fillna(df[''].mode()[0])
#df[''] = df[''].fillna(df[''].mean())


df['Mortgage'] = df['Mortgage'].fillna(df['Mortgage'].mean())
df['Personal Loan'] = df['Personal Loan'].fillna(df['Personal Loan'].mean())
df['Securities Account'] = df['Securities Account'].fillna(df['Securities Account'].mean())


#Checking for Null
df.isna().sum()


ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [28]:
# Encoding categorical data
# X is independent
# Y is dependent

#Values [Slice, Columns]
#.drop drops the inputed column

df = df.drop('ID',axis=1)

X = df.drop('CreditCard', axis =1)
y = df['CreditCard']

print("The values of X are",X)

print("The values of Y are",y)

The values of X are       Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0      25           1      49     91107       4    1.6          1       0.0   
1      45          19      34     90089       3    1.5          1       0.0   
2      39          15      11     94720       1    1.0          1       0.0   
3      35           9     100     94112       1    2.7          2       0.0   
4      35           8      45     91330       4    1.0          2       0.0   
...   ...         ...     ...       ...     ...    ...        ...       ...   
4995   29           3      40     92697       1    1.9          3       0.0   
4996   30           4      15     92037       4    0.4          1      85.0   
4997   63          39      24     93023       2    0.3          3       0.0   
4998   65          40      49     90034       3    0.5          2       0.0   
4999   28           4      83     92612       3    0.8          1       0.0   

      Personal Loan  Securities

In [29]:
X.head()

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   25           1      49     91107       4    1.6          1       0.0   
1   45          19      34     90089       3    1.5          1       0.0   
2   39          15      11     94720       1    1.0          1       0.0   
3   35           9     100     94112       1    2.7          2       0.0   
4   35           8      45     91330       4    1.0          2       0.0   

   Personal Loan  Securities Account  CD Account  Online  
0            0.0                 1.0           0       0  
1            0.0                 1.0           0       0  
2            0.0                 0.0           0       0  
3            0.0                 0.0           0       0  
4            0.0                 0.0           0       0

In [30]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: CreditCard, dtype: int64

In [31]:
# Splitting Train and Test values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [32]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

SVM - Support Vector Machine

In [33]:
# import svc
from sklearn.svm import SVC

# Creating a instance
classifier = SVC(kernel='rbf',random_state=None)

# Fitting the model
classifier.fit(X_train, y_train)

SVC()

In [34]:
classifier.intercept_

array([-0.46308174])

In [35]:
classifier.n_support_

array([1254,  922], dtype=int32)

In [36]:
classifier.support_vectors_

array([[ 1.46009961,  1.48062755, -1.13241577, ..., -0.34744389,
        -0.26023878,  0.82380645],
       [ 1.11082929,  1.04398203, -0.73942595, ..., -0.34744389,
        -0.26023878, -1.21387736],
       [ 0.6742414 ,  0.6073365 , -0.93592086, ..., -0.34744389,
        -0.26023878,  0.82380645],
       ...,
       [ 1.28546445,  1.39329845, -1.13241577, ...,  2.87816254,
         3.84262485,  0.82380645],
       [-0.11161681, -0.00396724, -0.10627568, ..., -0.34744389,
        -0.26023878,  0.82380645],
       [ 1.63473476,  1.65528577, -0.0189446 , ...,  2.87816254,
        -0.26023878, -1.21387736]])

In [37]:
# Predicting the values
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Confusion matrix
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)

cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)

[[2466   19]
 [ 845  170]]
[[1035   10]
 [ 393   62]]


In [39]:
# Accuracy
accuracy_train = accuracy_score(y_train, y_pred_train)
print((accuracy_train)*100, '%')

75.31428571428572 %


In [40]:
accuracy_test = accuracy_score(y_test, y_pred_test)
print((accuracy_test)*100, '%')

73.13333333333333 %


In [41]:
from sklearn.metrics import classification_report

# Additional performance metrics
report_train = classification_report(y_train, y_pred_train)
report_test = classification_report(y_test, y_pred_test)

print("Training Set Metrics:")
print(report_train)

print("Testing Set Metrics:")
print(report_test)

# Feature weights (coefficients) for linear kernel
if classifier.kernel == 'linear':
    feature_weights = classifier.coef_
    print("Feature Weights:")
    print(feature_weights)


Training Set Metrics:
              precision    recall  f1-score   support

           0       0.74      0.99      0.85      2485
           1       0.90      0.17      0.28      1015

    accuracy                           0.75      3500
   macro avg       0.82      0.58      0.57      3500
weighted avg       0.79      0.75      0.69      3500

Testing Set Metrics:
              precision    recall  f1-score   support

           0       0.72      0.99      0.84      1045
           1       0.86      0.14      0.24       455

    accuracy                           0.73      1500
   macro avg       0.79      0.56      0.54      1500
weighted avg       0.77      0.73      0.65      1500



In [44]:
import numpy as np

# Collect user input for the 12 features
age = float(input("Enter Age: "))
experience = float(input("Enter Experience: "))
income = float(input("Enter Income: "))
zip_code = float(input("Enter ZIP Code: "))
family = float(input("Enter Family: "))
ccavg = float(input("Enter CCAvg: "))
education = float(input("Enter Education (1, 2, 3): "))
mortgage = float(input("Enter Mortgage: "))
personal_loan = float(input("Personal Loan (0 for No, 1 for Yes): "))
securities_account = float(input("Securities Account (0 for No, 1 for Yes): "))
cd_account = float(input("CD Account (0 for No, 1 for Yes): "))
online = float(input("Online (0 for No, 1 for Yes): "))

# Organize user input into a numpy array
user_input = np.array([age, experience, income, zip_code, family, ccavg, education, mortgage, personal_loan, securities_account, cd_account, online]).reshape(1, -1)

# Scale the user input using the same StandardScaler used for the training data
user_input_scaled = sc.transform(user_input)

# Make a prediction using the trained SVM model
prediction = classifier.predict(user_input_scaled)

# Print the prediction
if prediction == 1:
    print("The user is eligible for a Credit Card.")
else:
    print("The user is not eligible for a Credit Card.")


Enter Age: 35
Enter Experience: 8
Enter Income: 45
Enter ZIP Code: 91330
Enter Family: 4
Enter CCAvg: 1
Enter Education (1, 2, 3): 2
Enter Mortgage: 0
Personal Loan (0 for No, 1 for Yes): 0
Securities Account (0 for No, 1 for Yes): 0
CD Account (0 for No, 1 for Yes): 0
Online (0 for No, 1 for Yes): 0
The user is not eligible for a Credit Card.


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


0

In [46]:
import joblib

# Save the trained SVM model to a file
joblib.dump(classifier, 'svm_model.pkl')

# Save the StandardScaler object to a file
joblib.dump(sc, 'scaler.pkl')


['scaler.pkl']